version: "3.1"

services:
  redisDb:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypassword
    volumes:
      - redisDb:/data

volumes:
  redisDb:
    driver: local

  # db:
  #   container_name: postgres_container
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - .env.local
  #   ports:
  #     - "5432:5432"

  # adminer:
  #   container_name: adminer_container
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # nextjs:
  #   container_name: nextjs_container
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.local
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/nextjs
  #   environment:
  #     - NODE_ENV=development
